### ISSUE TITLE
上传成功，但是提示错误

### ISSUE THREAD

**Issue by kokojacket** [ZenEcho/PLExtension#10]
![image](https://github.com/ZenEcho/PLExtension/assets/74887370/2673c3f2-41da-42c6-a305-4e726fc78be7)

**Comment by ZenEcho** [comment]
可以将你上传的图片发生到这里吗？如果是链接粘贴的就回复链接

**Comment by kokojacket** [comment]
![Clip_2024-04-20_21-41-25](https://github.com/ZenEcho/PLExtension/assets/74887370/eb5c335d-b34e-4dbc-827d-e52b73d07de4)
![image](https://github.com/ZenEcho/PLExtension/assets/74887370/16526dd8-5e9e-4868-b849-8b7a01526cc1)


现在这个edge，上传任何图都是这样不知道为什么

**Comment by ZenEcho** [comment]
> ![Clip_2024-04-20_21-41-25](https://private-user-images.githubusercontent.com/74887370/324181185-eb5c335d-b34e-4dbc-827d-e52b73d07de4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzIwODksIm5iZiI6MTcxMzY3MTc4OSwicGF0aCI6Ii83NDg4NzM3MC8zMjQxODExODUtZWI1YzMzNWQtYjM0ZS00ZGJjLTgyN2QtZTUyYjczZDA3ZGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAzNTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OTcwZjM5NGExMDcyYzY3MjA1ZGNkYjVmOWEwMGQ1ZTI1OWJhMzczNmEzOTdhZDE4ODhhNTllNTk3NzYwMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.57hEcS9Pt5ESmjqiIh3PgqLUUdMzCH6nQJu8zZXaWmc) ![图像](https://private-user-images.githubusercontent.com/74887370/324181196-16526dd8-5e9e-4868-b849-8b7a01526cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzIwODksIm5iZiI6MTcxMzY3MTc4OSwicGF0aCI6Ii83NDg4NzM3MC8zMjQxODExOTYtMTY1MjZkZDgtNWU5ZS00ODY4LWI4NDktOGI3YTAxNTI2Y2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAzNTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTRlODVjYTg3OWZjZWVmNDBhOWE2NDI1NWM4N2EyMTY0N2MwOWQyMGYyNTY2OGJmMzM3ODJjYmM0ZTA0OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IsOguCbghW0A7xrXdu7QoaOxdiXsUT11_db30ki4Jr8)
> 
> 现在这个edge，上传任何图都是这样不知道为什么

你这个图片里的提示看起来没问题的，当 多条提示 时看最后一个提示就好了。
原因的话 有空我再分析一下。

**Comment by kokojacket** [comment]
我感觉应该是文件名称重复导致的。

**Comment by lorenzohee** [comment]
同样报这个错误

我的环境：
win10 + edge
ubuntu + edge

F12查看http请求，返回的数据是正确的，图床中也正确上传了，怀疑是解析返回值的时候错误

**Comment by lorenzohee** [comment]
问题查出来了：
我使用的是简单图床，在成功返回后，返回的是JSON格式的字符串（并不是JSON），获取ImageUrl的时候就会报错

代码
```
// Chromium/js/popup.js(302行)
// res 为JSON格式字符串
case 'EasyImages':
          toastItem({
            toast_content: res.message
          })
          imageUrl = res.url
          break;
```

盼：早日更新，我还等着用呢

**Comment by ZenEcho** [comment]
> 简单图床

我测试了简单图床最新版2.8.4，提示都是正确的。

> 问题查出来了： 我使用的是简单图床，在成功返回后，返回的是JSON格式的字符串（并不是JSON），获取ImageUrl的时候就会报错
> 
> 代码
> 
> ```
> // Chromium/js/popup.js(302行)
> // res 为JSON格式字符串
> case 'EasyImages':
>           toastItem({
>             toast_content: res.message
>           })
>           imageUrl = res.url
>           break;
> ```
> 
> 盼：早日更新，我还等着用呢

1.早期的简单图床返回的是字符串，随着简单图床更新返回json后我移除了字符串转json的代码。
2.测试了简单图床最新版的2.8.4，是有正确获取到url的。
# 解决
所以如果简单图床返回错误，更新一下图床就好了。
