### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by wxhdrsa7** [ZenEcho/PLExtension#4]
1:现在是配置了一个图床之后，不能配置其他的了，要不然会被替换掉。建议优化一下可以配置很多图床进行切换
2:我使用两个都是蓝空图床,现在是只能配置一个,看能不能配置多个然后进行切换

**Comment by ZenEcho** [comment]
好的，已采纳。

**Comment by ZenEcho** [comment]
已完成
