### ISSUE TITLE
右侧的这个图标能不能改的小一点，偏下方一点呢？

### ISSUE THREAD

**Issue by himonster1** [ZenEcho/PLExtension#5]
https://file.uhsea.com/2309/78c8dbeccac6ffbeae5608869188bb65W9.png

改成一个小正方形，往下面放一点，或者可以自己拖动改变位置，另外图标真的太丑了

**Comment by ZenEcho** [comment]
在配置页面的 侧边栏按钮可以修改的

**Comment by himonster1** [comment]
拖不动 灰色的

<img width="469" alt="image" src="https://github.com/ZenEcho/PLExtension/assets/77065609/21251d91-61c3-4e7b-be51-d584dd3d0b8d">

**Comment by ZenEcho** [comment]
> 拖不动 灰色的
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/77065609/266041681-21251d91-61c3-4e7b-be51-d584dd3d0b8d.png">

右边那个灰块是可以用鼠标拖动的
