### ISSUE TITLE
简单图床通过插件上传有bug

### ISSUE THREAD

**Issue by KrisFlowerss** [ZenEcho/PLExtension#6]
token设置完后进行上传操作 确实能够上传到服务器上 但是上传完毕后插件返回的地址是undefined
并且通过f12检查：

"result":"success","code":200,"url":"https://img.zhuxxx.link/i/2023/09/23/s7f9aa-3.gif","srcName":"shake-kaninayuta","thumb":"https://img.zhuefy.link/application/thumb.php?img=/i/2023/09/23/s7f9aa-3.gif","del":"https://img.zxxxx.link/application/del.php?

可以看出正确上传  应该是json的获取解析有问题
并且通过另一个坛友的测试 表示确实无力回天并得出和我相同的结论（上）  在ns问过 作者可以看看
（谷歌浏览器）

**Comment by ZenEcho** [comment]
需要升级一下简单图床的版本到2.8.3(目前最新版)，但目前上传提示仍有错误但不影响使用，下个版本将会修复

**Comment by ZenEcho** [comment]
> 需要升级一下简单图床的版本到2.8.3(目前最新版)，但目前上传提示仍有错误但不影响使用，下个版本将会修复

检查了一下这个返回错误的bug不打算修复，因为是简单图床写错返回键值了，目前已通知简单图床作者。等简单图床作者修复吧
![image](https://github.com/ZenEcho/PLExtension/assets/56901101/00bb39c7-b9cf-4464-aa39-3c03b5d1c2d4)

**Comment by KrisFlowerss** [comment]
收到🫡
