### ISSUE TITLE
在关闭拖拽上传后仍然会添加类名为btn的样式，影响网站原有的样式

### ISSUE THREAD

**Issue by huanfe1** [ZenEcho/PLExtension#9]
在关闭拖拽上传后仍然会添加类名为btn的样式，影响网站原有的样式

![image](https://github.com/ZenEcho/PLExtension/assets/41602338/f2d23a9b-3aa1-4837-bd76-e39ef7c9672c)

**Comment by ZenEcho** [comment]
感谢反馈！已处理，很快就能更新推送。
